# --- !Ups

--- Resource categories
create table "resourceCategory" (
  "id" VARCHAR generated BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "name" VARCHAR
);

insert into "resourceCategory"
("name")
values
('Breads'),
('Vegetables'),
('Meat'),
('Sea Food'),
('Dairy'),
('Grains (pasta, rice, etc)'),
('Fruits'),
('Condiments (sauces, pesto, etc)'),
('Drinkables'),
('Miscellaneous (Chips, biscuits, cooking oils, etc)');

--- Resource amount labels
create table "resourceAmountLabel" (
  "id" VARCHAR generated BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "name" VARCHAR
);

insert into "resourceAmountLabel"
("name")
values
('Quantity'),
('Kg'),
('Pieces'),
('Packets'),
('Cans'),
('Boxes'),
('Bottles'),
('Crates');

--- Supplies
create table "supply" (
  "id" VARCHAR NOT NULL PRIMARY KEY,
  "userID"  VARCHAR NOT NULL REFERENCES "user",
  "resource" VARCHAR,
  "resourceCategoryID" LONG REFERENCES "resourceCategory",
  "amount" INTEGER,
  "amountLabelID" LONG REFERENCES "resourceAmountLabel"
);


# --- !Downs

drop table "resourceCategory";
drop table "resourceAmountLabel";
drop table "supply";
