# --- !Ups

CREATE TABLE "users" (
    "id" bigint generated by default as IDENTITY (start with 1) NOT NULL PRIMARY KEY,
    "username" varchar NOT NULL,
    "password" varchar NOT NULL
);

# --- !Downs

DROP TABLE "users" if EXISTS;
