# --- !Ups

create table "musics" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "album_id" bigint not null references "albums",
  "title" varchar not null,
  "lyrics" varchar not null
);

# --- !Downs

drop table "musics" if exists;
