# --- !Ups

create table "albums" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar
);

# --- !Downs

drop table "albums" if exists;
