# --- !Ups

create table "musics" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "title" varchar not null,
  "lyrics" varchar not null,
  "year" int
);

# --- !Downs

drop table "musics" if exists;
